data:
  path: data/lsun_cars_yolo64/images/*.jpg
  fid_file: data/lsun_cars_yolo64/fid_files/cars.npz
  random_crop: True
model:
  bounding_box_generator_kwargs:
    scale_range_min: [0.20, 0.16, 0.16]
    scale_range_max: [0.25, 0.2, 0.2]
    translation_range_min: [-0.22, -0.12, 0.]
    translation_range_max: [0.22, 0.12, 0.]
  generator_kwargs:
    range_v: [0, 0.5]
    fov: 10
training:
  out_dir:  out/lsunCarsYolo64
  validate_every: 1000
  visualize_every: 500