data:
  path: data/lsun_cars_yolo256/images/*.jpg
  fid_file: data/lsun_cars_yolo256/fid_files/cars.npz
  random_crop: True
  img_size: 256
model:
  bounding_box_generator_kwargs:
    scale_range_min: [0.16, 0.16, 0.16]
    scale_range_max: [0.2, 0.2, 0.2]
    translation_range_min: [-0.05, -0.05, 0.]
    translation_range_max: [0.05, 0.05, 0.]
  generator_kwargs:
    range_v: [0, 0.5]
    fov: 10
training:
  out_dir:  out/lsunCarsYolo256
  validate_every: 1000
  visualize_every: 500